### ISSUE TITLE
firmware update

### ISSUE THREAD

**Issue by aysegulucar2016** [ROBOTIS-GIT/ROBOTIS-OP2#4]
Hi,

When the firmware installation in robotis-op2 used? What is its aim? We cant see an file about cm-740 in robotis-op2 even. All files is about cm-730.

When I used it, 
bps of the motors are failing. Some of them are 57600 bps and some of them are 1mbs.

Thanks

**Comment by ROBOTIS-zerom** [comment]
In general, you should not use the firmware installer if there are no problem using the OP2. 
If there is a critical issue with the CM-730 or MX-28 and the firmware that fixes the issue is released, use this program to download the updated firmware to the device. 

https://sourceforge.net/p/darwinop/code/HEAD/tree/trunk/robotisop2/Linux/project/firmware_installer/
As you can see, the firmware installer of ROBOTIS-OP2 contains the firmware file of CM-740. If you see the firmware file of the CM-730, it is most likely the source of the ROBOTIS-OP.
Downloading the CM-730 firmware to the CM-740 can cause problems, so be careful.

If the baudrate of some motors comes to 57600 bps, it may be wrong during firmware installation. 
Change the ID and baudrate to the correct values using the Dynamixel Wizard on Windows or dxl_monitor on Linux.

**Comment by aysegulucar2016** [comment]
Thanks for clear answer.
